### ISSUE TITLE
enum  cannot be embedded in struct like this：[14397]

### ISSUE THREAD

**Issue by xiaokezhou** [eProsima/Fast-DDS-Gen#107]
struct  Foo{

  enum Bar{
      a,
      b
  };

  Bar bar;

};

_**Change to below, generator works:**_

struct  Foo{

   enum Bar{
      a,
      b
  }bar;

};

_Can you fix this bug ? @Eprosima   ,because I have hundreds of IDL files to deal with_

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @xiaokezhou,

The [standard](https://www.omg.org/spec/IDL/4.2/About-IDL/) does not allow the definition of enumerations inside the struct definition. Therefore, what you are reporting it is not really an issue.

However, you have found indirectly a bug. As you report, in the second case, although the generated files does not include the variable `bar` in the struct, there is no failing message and the type support files are generated though not as the user expects.

I am going to open a new issue with this bug and close this issue as it is the expected behavior according to the specification.
