### ISSUE TITLE
[16938] fastddsgen throws exception when executing on .idl file with bitset and using flag -typeobject

### ISSUE THREAD

**Issue by kylesemelka-figure** [eProsima/Fast-DDS-Gen#148]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

FastDDSGen should produce valid output files when generating from .idl files with bitsets and passing the `-typeobject` flag.

### Current behavior

`fastddsgen` fails to generate output files when using `-typeobject` flag on an idl file with a bitset.

### Steps to reproduce

Execute: `fastddsgen -typeobject test.idl`

_test.idl_:
```
bitset test {
  bitfield<1> a;
};
```

### Fast DDS version/commit

Branch: 2.8.0
Commit hash: `aa485fc7df93e7e4a343dfc0c2bd3621716e96c6`

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

Platform: Ubuntu 22.04 amd64

### Relevant log output

```shell
$ fastddsgen -typeobject test.idl

Loading templates...
Processing the file test.idl...
ERROR<Exception>: no such attribute: union in template context [bitset_type]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.eprosima.fastdds.solution.Project.getIDLIncludeFiles()" because "project" is null
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:401)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1474)
```

**Comment by MRicoIE2CS** [comment]
Hi @kylesemelka-figure ,

This issue was transferred to Fast-DDS-Gen repository.
We are not able to reproduce the issue, as with the idl provided, no exception was thrown. We have tried using fastddsgen
We may need more information in order to help you. Please, could you specify the following?
- fastddsgen version
- java and graddle version
- Is that bitset the only element in the idl you are using?
- Despite the exception you got, are the files being generated?

**Comment by kylesemelka-figure** [comment]
1. fastddsgen version: `2.1.0+dfsg`
2. Java version:
```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)
```
How can I check the "graddle" version? Please note I did not build from source, I used `sudo apt-get install fastddsgen` to install the program.
3. Yes, the code sample I provided is the full idl file.
4. No, the files do not get generated when I see the exception. When I remove the `-typeobject` flag, the files are generated successfully.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @kylesemelka-figure 

In that case is what is expected. Fast DDS-Gen started supporting Gradle 7.0 and newer versions since [release v2.2.0](https://github.com/eProsima/Fast-DDS-Gen/releases/tag/v2.2.0). And Gradle only started supporting Java 17 since [release 7.3](https://docs.gradle.org/7.3/release-notes.html). You can find the gradle version with the `gradle -v` command if you have it installed in your system. If you are using the `gradlew` script provided in the repository then you can find the version in [this file](https://github.com/eProsima/Fast-DDS-Gen/blob/v2.1.0/gradle/wrapper/gradle-wrapper.properties). In Fast DDS-Gen v2.1.0, the Gradle version being used is 6.4.

Please, upgrade your Fast DDS-Gen or else downgrade the dependencies. I hope that your issue is solved with this information. Please, if it is solved, remember to close the issue. Thanks for your contribution!

**Comment by kylesemelka-figure** [comment]
Sorry, I am not clear on what I need to do to get this snippet to generate using fastddsgen version 2.1.0+dfsg. I have downgraded the java runtime to Java 11, and am still getting an error from fastddsgen, however the error is a bit different.

Is there another dependency I need to downgrade besides Java? Are bitsets generated with typeobject flag supported in this version of fastddsgen?

```
$ java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode)

$ fastddsgen -version            
fastddsgen version 2.1.0+dfsg

$ fastddsgen -typeobject test.idl
Loading templates...
Processing the file test.idl...
ERROR<Exception>: no such attribute: union in template context [bitset_type]
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:401)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1474)
```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @kylesemelka-figure 

I have tested with the following Dockerfile and everything works as expected. The docker image is built over Ubuntu 22.04 (your reported OS), installs Java 11 and uses the Gradle from the script provided in the repository. It clones the repository and checkouts the version v2.1.0 which is the one you are using. The same IDL snippet as the one in the opening ticket is provided. Running Fast DDS-Gen with the `typeobject` option does not throw any error. Can you please confirm that the Dockerfile builds also for you? Are some other step that is required to reproduce your issue?

```
FROM ubuntu:22.04

RUN apt update
RUN apt install -y \
        git \
        gcc \
        openjdk-11-jdk

WORKDIR /home
RUN git clone https://github.com/eProsima/Fast-DDS-Gen.git && \
    cd Fast-DDS-Gen && \
    git checkout v2.1.0 && \
    bash gradlew assemble

RUN echo 'bitset test {bitfield<1> a;};' > test.idl
RUN bash /home/Fast-DDS-Gen/scripts/fastddsgen -typeobject test.idl
```

**Comment by kylesemelka-figure** [comment]
@JLBuenoLopez-eProsima Thanks for the Dockerfile example. Yes, this builds for me. The only difference between this Dockerfile and the failing environment is that `fastddsgen` is built from source in your example. We are installing `fastddsgen` through the apt package manager. The following Dockerfile does not build, even though the same version of `fastddsgen` is installed:
```
FROM ubuntu:22.04

RUN apt update
RUN apt install -y \
        fastddsgen \
        openjdk-11-jdk

WORKDIR /home

RUN echo 'bitset test {bitfield<1> a;};' > test.idl
RUN bash fastddsgen -typeobject test.idl
```

This issue is not too bad to resolve for us, but we only want to build from source if we absolutely have to. My conclusion is that there must be something "special" about how the fastddsgen package was built for distribution through apt, and to prevent any further issues we should avoid using that package.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @kylesemelka-figure 

Regretfully, eProsima is not distributing that package in apt universe. You may consider opening a ticket [here](https://packages.ubuntu.com/jammy/devel/fastddsgen) so the maintainer knows about the issue. It seems like the Gradle version used to build the project is lower than 6.4 because I have checked that the Java installed with the package by default is Java 11. I have been unable to find the complete build information though.

Another option is to use the fastddsgen binary package distributed by eProsima. This is done within the [Vulcanexus](https://docs.vulcanexus.org/en/latest/index.html) ecosystem which depends on ROS 2. [Here](https://docs.vulcanexus.org/en/latest/rst/installation/linux_binary_installation.html) the installation manual with the steps to include eProsima's (and ROS 2) repository. The package can be installed with `apt install vulcanexus-humble-fastddsgen`. However, there is another caveat (besides installing ROS 2 dependencies), Vulcanexus distribution is continuously updating to the latest version, so if you require to have a Fast DDS-Gen version pinned down, you should be aware that this might not help.

**Comment by kylesemelka-figure** [comment]
Thanks for the clarification. Made a bug ticket for them here: https://bugs.launchpad.net/ubuntu/+source/fastddsgen/+bug/2004231
