### ISSUE TITLE
fastrtpsgen generates wrong absolute include pathes [5686]

### ISSUE THREAD

**Issue by 0loid** [eProsima/Fast-DDS-Gen#33]
When you use nested idl files with 
`#include "idltypeB.idl"`
in "idltypeA.idl", the generator transforms it into:
`#include "<absolute path to where the idl files are >/idltypeB.h"`

If you hold the generated files in a different directory than the idl files with " -d <path>: sets an output directory for generated files." this will fail on compile time.

Expected Behavior:
The generator should translate relative includes to relative includes.
e.g.
`#include <idltypB.idl> --> #include <idltypeB.h>` 
From my point of view the user/developer is responsible to have all the nessesary files in its compilers include pathes.
Thanks!

**Comment by eirikhex** [comment]
I have a similar issue:
I have the following structure and run fastrtpsgen -replace -cs -I includes -d output includes/special1/special1.idl includes/special2/special2.idl
.
├── includes
│   ├── common
│      ├── common.idl
│   ├── special1
│      └──special1.idl <- has #include "common/common.idl"
│   └── special2
│      └── special2.idl <- has #include "common/common.idl"
└── output
       ├── common.h
       ├── common.cxx
       ├── special1.h <- has #include "common/common.h"
       ├── special1.cxx
       ├── special2.h <- has #include "common/common.h"
       ├── special2.cxx
       └── .....

This makes problems since there is no "common/common.h". The include keeps its relative path in the code include directive, but the generated file are not placed in the correct relative folder..

**Comment by eirikhex** [comment]
I did however find a workaround to accomplish to flatten the the includes for the generated files. for the example above this would be to run:
```
fastrtpsgen -replace -cs -I includes -I includes/common -d output includes/special1/special1.idl includes/special2/special2.idl
```

**Comment by RFRIEDM-Trimble** [comment]
I have ran into this too trying to generate into a different directory than where the IDL files are when the IDL uses `#include`.

**Comment by Rubyonlyx** [comment]
have the same structure  problem too

**Comment by briansoe66** [comment]
https://github.com/eProsima/Fast-CDR/pull/139 adds a cmake function (fastddsgen.cmake), that will run fastddsgen, and move the header/source, so that the output include folder structure mirrors the input idl folder structure. The PR does not handle absolute paths.

**Comment by JLBuenoLopez-eProsima** [comment]
Fast DDS-Gen v3.0.0 fixes this issue.
