### ISSUE TITLE
Failed to load native library 'libnative-platform.so' for Linux amd64

### ISSUE THREAD

**Issue by CHAOHUILI** [eProsima/Fast-DDS-Gen#405]
![image](https://github.com/user-attachments/assets/c32bfbb1-85c6-476b-b855-d2835ab1f444)
can't found .so,   please help

**Comment by JesusPoderoso** [comment]
Hi @CHAOHUILI,
which JDK have you installed?

**Comment by CHAOHUILI** [comment]
![image](https://github.com/user-attachments/assets/3d1bf08b-3536-4fee-8f61-c83517a6d96c)
yes,i installed.

**Comment by CHAOHUILI** [comment]
![image](https://github.com/user-attachments/assets/dea88728-1134-49d2-9cfd-b0ff25a7081f)
hi @JesusPoderoso

**Comment by JesusPoderoso** [comment]
Hi @CHAOHUILI, 
we have never experienced that gradle error. Looking for more information we have reached [this thread](https://github.com/gradle/gradle/issues/1493), which hints the issue may be caused by the [lack of user permissions](https://github.com/gradle/gradle/issues/1493#issuecomment-344715852). Hope it helps.
